config/routes.rb
Rails.application.routes.draw do

  resources :produces
  root  'home#index'

  get   'home'          =>  'home#index'
  get   'about'         =>  'home#about'
  get   'contact'       =>  'home#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produce.rb
class Produce < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
    @page_header = "About Us"
  end

  def contact
    @page_header = "Contact Us"
  end

end

app/controllers/produces_controller.rb
class ProducesController < ApplicationController
  before_action :set_produce, only: [:show, :edit, :update, :destroy]

  # GET /produces
  # GET /produces.json
  def index
    @produces = Produce.all
    @page_header = "Produce"
  end

  # GET /produces/1
  # GET /produces/1.json
  def show
  end

  # GET /produces/new
  def new
    @produce = Produce.new
  end

  # GET /produces/1/edit
  def edit
  end

  # POST /produces
  # POST /produces.json
  def create
    @produce = Produce.new(produce_params)

    respond_to do |format|
      if @produce.save
        format.html { redirect_to @produce, notice: 'Produce was successfully created.' }
        format.json { render :show, status: :created, location: @produce }
      else
        format.html { render :new }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produces/1
  # PATCH/PUT /produces/1.json
  def update
    respond_to do |format|
      if @produce.update(produce_params)
        format.html { redirect_to @produce, notice: 'Produce was successfully updated.' }
        format.json { render :show, status: :ok, location: @produce }
      else
        format.html { render :edit }
        format.json { render json: @produce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produces/1
  # DELETE /produces/1.json
  def destroy
    @produce.destroy
    respond_to do |format|
      format.html { redirect_to produces_url, notice: 'Produce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produce
      @produce = Produce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produce_params
      params.require(:produce).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/produces_helper.rb
module ProducesHelper
end

app/views/home/_home_carousel.html.erb
<div class="row">
   <div class="col-md-12">
     <div class="carousel slide multi-item-carousel" id="theCarousel">
       <div class="carousel-inner">
         <div class="item active">
           <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/f44336/000000" class="img-responsive"></a></div>
         </div>
         <div class="item">
           <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/e91e63/000000" class="img-responsive"></a></div>
         </div>
         <div class="item">
           <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/9c27b0/000000" class="img-responsive"></a></div>
         </div>
         <div class="item">
           <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/673ab7/000000" class="img-responsive"></a></div>
         </div>
         <div class="item">
           <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/4caf50/000000" class="img-responsive"></a></div>
         </div>
         <div class="item">
           <div class="col-xs-4"><a href="#1"><img src="http://placehold.it/300/8bc34a/000000" class="img-responsive"></a></div>
         </div>
       </div>
       <a class="left carousel-control" href="#theCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
       <a class="right carousel-control" href="#theCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
     </div>
   </div>
 </div>

app/views/home/_home_msg_slider.html.erb
<div id="home-msg-slider" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#home-msg-slider" data-slide-to="0" class="active"></li>
    <li data-target="#home-msg-slider" data-slide-to="1"></li>
    <li data-target="#home-msg-slider" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="text-center">
        <h2 class="home-msg">Mauris ullamcorper purus sit amet nulla.</h2>
      </div>
    </div>

    <div class="item">
      <div class="text-center">
        <h2 class="home-msg">Sed sagittis.</h2>
      </div>
    </div>

    <div class="item">
      <div class="text-center">
        <h2 class="home-msg">Vestibulum ac est lacinia nisi venenatis!</h2>
      </div>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<section id="about-box">
  <p>
    <%= simple_format "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus." %>
  </p>
</section>

app/views/home/contact.html.erb
<section>
  <div class="row">
    <div class="col-md-4 col-sm-12 contact-info text-center">
      <h1 class="contact-info-header">CONTACT INFO</h1>
      <p>
        kpowell1@rediff.com
      </p>
      <p>
        15 Grim Parkway
      </p>
      <p>
        7-(533)316-6900
      </p>
    </div>
    <div class="col-md-8 col-sm-12 contact-form">
      <h1 class="contact-form-header">CONTACT FORM</h1>
      <%= react_component('ContactForm') %>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'home_msg_slider' %>
<%#= render 'home_carousel'%>

app/views/layouts/_header.html.erb
<header class="main-header">
  <h1 class="page-header"><%= @page_header %></h1>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" id="main-nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#toggle-nav">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'William Farm Produce', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="toggle-nav">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "About Us", about_path %>
        </li>
        <li>
          <%= link_to "Produce", produces_path %>
        </li>
        <li>
          <%= link_to "Contact Us", contact_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WilliamProduceRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="outer-wrapper">
      <%= render 'layouts/nav' %>
      <div class="inner-wrapper container">
        <% if @page_header && @page_header != 'home' %>
          <%= render 'layouts/header' %>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/produces/_form.html.erb
<%= simple_form_for(@produce) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/produces/edit.html.erb
<h1>Editing Produce</h1>

<%= render 'form', produce: @produce %>

<%= link_to 'Show', @produce %> |
<%= link_to 'Back', produces_path %>

app/views/produces/index.html.erb
<section>
  <% @produces.each do |produce| %>
    <div class="produce-box">
      <div class="side-image col-md-4">
        <%= image_tag "carousel/#{produce.name.parameterize.underscore}", size: '300x250', alt: produce.name, class: 'produce-img img-responsive' %>
      </div>
      <div class="produce-info col-md-8">
        <h3><%= produce.name %></h3>
        <div class="produce-description">
          <p>
            <%= produce.description %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/produces/new.html.erb
<h1>New Produce</h1>

<%= render 'form', produce: @produce %>

<%= link_to 'Back', produces_path %>

app/views/produces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @produce.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @produce.description %>
</p>

<%= link_to 'Edit', edit_produce_path(@produce) %> |
<%= link_to 'Back', produces_path %>